### ISSUE TITLE
正则问题

### ISSUE THREAD

**Issue by zzm305305** [daxingplay/css-combo#32]
辛苦看下，这的正则表达式是不是有些问题。
https://github.com/daxingplay/css-combo/blob/master/lib/combo.js#L274
![image](https://cloud.githubusercontent.com/assets/3906299/26402008/24050862-40bb-11e7-9526-a2f67953a5e3.png)

**Comment by daxingplay** [comment]
Thanks for your bug report, this issue has been fixed. Version 0.5.5 released.
