### ISSUE TITLE
csscombo.build为什么不能用？

### ISSUE THREAD

**Issue by renhao** [daxingplay/css-combo#6]
提示说不是内部或外部命令
版本是csscombo v0.2.4 (CSS Module Compiler)

全局安装npm install -g css-combo

**Comment by HeDonglin** [comment]
cfg 参数可以配置以下选项：compress: {Boolean} 是否压缩，默认为true，
CSSCombo.build(src, dest, cfg, function(err){ callback(); });这个cgf怎么填,搞了很久也不明白写
我在gulp中gulpfile.js文件中设置
//css语法检查
gulp.task('css', function() {
    var cssSrc = 'src/**/index.combo.css',
        csscomSrc = 'src/css/index.css',
        compress = 'compress:{true}'
        csscomDst = 'src/css',
        cssDst = 'dist/css/';
    gulp.src(cssSrc)
        .pipe(plumber())//发生错误禁止停止gulp
        // .pipe(csslint('.csslintrc'))//css规则
        // .pipe(csslint.reporter())
        .pipe(csscombo.build(csscomSrc,csscomDst,compress)
        // .pipe(minicss())//压缩文件
        // .pipe(concat('cssSrc'))//合并文件
        // .pipe(rename({suffix:''}))//重新命名
        // .pipe(gulp.dest(cssDst));//分配文件到路径
加入compress后就发生错误,去掉compress就可以运行

**Comment by HeDonglin** [comment]
少了一个),我加上去后还是不能压缩

**Comment by daxingplay** [comment]
@HeDonglin compress 应该是个 object 哈。应该这么写：

```
.pipe(csscombo.build(csscomSrc, csscomDst, { compress: true }))
```
